### ISSUE TITLE
CI enhancement

### ISSUE THREAD

**Issue by lre12** [23-OSSCA-python-mysql-replication/python-mysql-replication#1]
- docker-compose mysql image 수정 및 추가
    - mysql 8 추가에 따른 테스트 개선
- local에서 테스트할 수 있는 docker-compose 추가
    - github actions 동작 시 actions의 container가 아닌, docker-compose container 위에서 테스트 수행되도록 수정
- test coverage & report 추가

**Comment by dongwook-chan** [comment]
CI 함께하실 분들 댓글 달아주세요~~
