### ISSUE TITLE
Fix commands that change since MySQL 8.0.22

### ISSUE THREAD

**Issue by davinc71998** [23-OSSCA-python-mysql-replication/python-mysql-replication#10]
### 이슈
* MySQL 8.0.22 이후 변경된 복제 관련 명령어 및 파라미터들이 존재합니다.
* MySQL 8.0.22 이전에 동일한 기능을 하는 명령어 및 파라미터들은 아직 사용할 수 있지만 추후 버전 업데이트에 따라 사라질 수 있습니다.

<br>

#### Show slave hosts

<img width="1048" alt="스크린샷 2023-07-23 오후 2 03 27" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/65767734/fb57b9a4-b3f9-43d4-b42d-4f794ee02321">

#### slave_uuid
* 변경 전
    <img width="1010" alt="스크린샷 2023-07-23 오후 2 08 06" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/65767734/4f4bbeea-5b20-4b13-b675-73d08476112b">
* 변경 후
    <img width="1026" alt="스크린샷 2023-07-23 오후 2 03 39" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/65767734/ead54c13-850b-44d3-9a78-3a9a75d84086">

#### 추후 문제가 발생할 수 있는 코드
https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/blob/92d3e6651657d7d2f2d941cd33e45fbd1437cab9/pymysqlreplication/binlogstream.py#L302-L305

<br>

### 요구사항
이와 같이 MySQL 8.0.22 버전 이후 변경된 복제 관련 명령어들을 찾고 버전 별 분기 처리를 추가하여 수정합니다.

<br>

### 참고자료
https://dev.mysql.com/doc/refman/8.0/en/show-slave-hosts.html

**Comment by soulee-dev** [comment]
#53
