### ISSUE TITLE
bug - PyMySQLReplicationTestCase.isMariaDB() 정상 동작하지 않음

### ISSUE THREAD

**Issue by cucuridas** [23-OSSCA-python-mysql-replication/python-mysql-replication#13]
### bug - PyMySQLReplicationTestCase.isMariaDB() 정상 동작하지 않음
----------
* 함수 설명 
해당 함수를 통해서 test 때 연결되어진 DBMS가 mysql 인지 mariaDB 인지 구별할 수 있습니다
```
    ...
    def isMariaDB(self):
        if self.__is_mariaDB is None:
            self.__is_mariaDB = "MariaDB" in self.execute("SELECT VERSION()").fetchone()
        return self.__is_mariaDB
    ...
```

* 문제 
fechone() 함수를 통해 실행시킨 결과 값은 tuple 형태로 전달 받고 있지만 현재 `"MariaDB" in self.execute("SELECT VERSION()").fetchone()` 구문은 string 타입의 데이터를 확인하고 있음에 따라 `isMariaDB` 함수는 항상 False를 반환하는 에러가 존재합니다
![image](https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/65060314/a4144a5e-13b7-4282-986d-276b02889a39)

**Comment by dongwook-chan** [comment]
원본 repo에서의 [PR](https://github.com/julien-duponchelle/python-mysql-replication/pull/409)이 머지되어 이슈를 종료합니다.
