### ISSUE TITLE
event 구현 - RAND_EVENT

### ISSUE THREAD

**Issue by heehehe** [23-OSSCA-python-mysql-replication/python-mysql-replication#2]
- https://mariadb.com/kb/en/rand_event/
- https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/tree/feature/rand-event

**Comment by dongwook-chan** [comment]
이벤트가 어떤 경우에 발생하는지는 이벤트 이름을 보면 답이 나올 것 같네요 :)
