### ISSUE TITLE
`Innodb_history_list_length` 증가

### ISSUE THREAD

**Issue by dongwook-chan** [23-OSSCA-python-mysql-replication/python-mysql-replication#38]
### 시나리오
MySQL로부터 이벤트를 받아오기 위해 다음 코드를 실행했습니다.
```
from pymysqlreplication import BinLogStreamReader

stream = BinLogStreamReader(connection_settings=MYSQL_SETTINGS,
                                blocking=True,
                                )

for binlogevent in stream:
    pass
```

### MySQL의 특성
이슈가 발생한 MySQL은 다음과 같은 특성이 있습니다.
- DML이 빈번히 발생 중

### 이슈
코드가 실행된 후에 MySQL의 `Innodb_history_list_length` 값이 꾸준히 증가하고 있습니다.
`Innodb_history_list_length`의 증가로 인해 MySQL에 다음과 같은 영향이 있을 것으로 예상됩니다.
* 사용자의 쿼리에 대한 응답 시간 증대

### 요구 사항
위 코드를 실행하더라도 `Innodb_history_list_length`가 증가하지 않도록 본 패키지 코드를 수정해주세요.

**Comment by dongwook-chan** [comment]
와... 그래프 넣으니까 이렇게 프로페셔널할수가!! 고생 많으셨습니다

**Comment by dongwook-chan** [comment]
정확합니다 ㅜㅜ 저는 8.0에서만 재현되었는데 혹시 5.7에서도 해보셨나요?

**Comment by dongwook-chan** [comment]
아마 5.7에서는 재현 안 되는게 맞을거에요!

**Comment by davinc71998** [comment]
https://www.notion.so/open-up/1-31a9b739d0514b008b03d438735c6955?p=ee5cb35b751b488eb3038bf108bc1708&pm=s
