### ISSUE TITLE
중의적으로 쓰이는 컬럼값 `None`🤔

### ISSUE THREAD

**Issue by dongwook-chan** [23-OSSCA-python-mysql-replication/python-mysql-replication#39]
Rows 이벤트에서 컬럼값 `None`이 가지는 의미

* 변경된 컬럼이 아닌 경우
* 변경된 컬럼값이 NULL인 경우
* MySQL에서 `Date` 혹은 `Datetime`형 컬럼값을 읽어왔는데 Python `Datetime.Date` 혹은 `Datetime.Datetime`으로 나타낼 수 없는 값인 경우 (표현 가능한 최솟값 미만이거나, 최댓값 초과)
    * 관련 upstream PR : https://github.com/julien-duponchelle/python-mysql-replication/pull/228

위 경우 모두 사용자에게 컬럼값이 `None`으로 전달되는데,
사용자 입장에서 세 가지 경우를 구분할 수 있는 방법이 없다.

세 가지 케이스를 구분할 수 있도록 개선해주세요.
개선이 불가능한 경우에도 Documentation의 Limitation 항목에 이슈를 적고, 우회책이 있다면 함께 적어주세요.

***

- 관련 notion 링크 : https://www.notion.so/open-up/origin-39-None-0f3f576ac4f141019ea8f9142fb1e67b?pvs=4

**Comment by heehehe** [comment]
https://github.com/julien-duponchelle/python-mysql-replication/pull/489 반영 완료
