### ISSUE TITLE
Docstring 수정 

### ISSUE THREAD

**Issue by ebang091** [23-OSSCA-python-mysql-replication/python-mysql-replication#43]
현재 멘토님께서 조언해주신대로 PEP8 (PEP 257)을 따르는 주석으로 수정하다가, 전체적인 주석이 그러한 상태라는 걸 알고나서 전반적으로 수정하고 싶다고 생각했습니다. 

동참하고 싶으신 분이 계시거나, 코드를 읽다가 이렇게 수정했으면 좋겠다는 의견이 있으셨다면 들려주신다면 감사할 것 같습니다.

### 1. event.py 등 각 py 파일의 docstring을 랜더링 시 개행된 형태로 수정합니다. 
<img width="769" alt="스크린샷 2023-08-06 오후 9 10 50" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/108053947/1a9f609b-00bb-43ef-8a7f-997f5566b49b">

꼴의 주석을 
<img width="758" alt="스크린샷 2023-08-06 오후 9 10 07" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/108053947/083ccf50-e403-49b4-a88c-58f6de0447b4">

위와 같은 식으로 바꾸려고 합니다. (예시입니다.)
멘토님께서 공유해주신 [문서](https://readthedocs.org/projects/python-code/downloads/pdf/latest/) 를 참고할 예정입니다. 

## 2. 가능하면 가독성을 높이는 쪽으로 Raises, Params 와 관련된 부분도 수정하려고 합니다. 
 같이 할 분이 계셔도 너무 좋을 거 같습니다 ㅎㅎ

**Comment by starcat37** [comment]
안녕하세요! 저도 참여하고 싶습니다:) 다만 제가 8/5 모임을 참여하지 못했는데 혹시 이 이슈와 관련해서 추가로 알아두어야 하는 사항이 있을까요?

**Comment by ebang091** [comment]
@starcat37 아니요! 추가적으로 아실 사항은 없는 것 같습니다!
@heehehe  오 노션도 공유해주셔서 너무 감사합니다! 노션 페이지 하나 파서 각자 수정하고 싶은 부분 나누어서 확인하면서 수정해도 넘 좋을 것 같아요 ㅎㅎㅎ
브랜치 하나 파는 것도 넘 필요한 것 같아요 적극 찬성입니다!!

**Comment by ebang091** [comment]
https://www.notion.so/open-up/docs-improve-comments-830b0113c0a2417e813305443c4de23d?pvs=4
@starcat37  @starcat37 @mjs1995 @mikaniz @sean-k1 3조 분들과 협업하고 싶어서 만들었습니다 ㅎㅎ

## 1. 노션이 더 협업하기 좋을 것 같아 위 사이트에 협업 공간 만들어두었습니다! 
자유롭게 편집해주셔도 됩니다..!

## 2. 브랜치 docs/improve-comments 로 파두었습니다 !

**Comment by heehehe** [comment]
@ebang091 오 정말 감사합니다!! 노션에서 작업하고 댓글로 의견들 남기겠습니다ㅎㅎ

(저희 3조 분들 필수 참여는 아니고, 원하시는 분들 자유롭게 함께해주시면 좋을 것 같습니다😃)

**Comment by dongwook-chan** [comment]
줄리앙이 너무 좋아하실 것 같아요 ㅜㅜ

**Comment by ebang091** [comment]
@cucuridas 물론이죠!! 환영입니다 😄

**Comment by heehehe** [comment]
https://github.com/julien-duponchelle/python-mysql-replication/pull/464 merge 완료로 issue close 하겠습니다 :)
당시에 작업하시느라 모두 고생 많으셨었어요!!😃
