### ISSUE TITLE
한국어로 작성된 주석 삭제

### ISSUE THREAD

**Issue by soulee-dev** [23-OSSCA-python-mysql-replication/python-mysql-replication#45]
https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/blob/45f823fa0ea6cd19de84b39aa78f5f181fafe18b/pymysqlreplication/event.py#L247

한국어로 작성되어 있는 주석을 삭제합니다

**Comment by dongwook-chan** [comment]
찾아주셔서 정말 감사합니다... 엉엉 ㅜㅜ
쥐구멍이 있다면 숨고 싶네요 ㅋㅋㅋ
부디 흑역사 거둬주세요...
