### ISSUE TITLE
`docker-compose.yaml`에 서비스 추가 (MySQL version 8 테스트 추가)

### ISSUE THREAD

**Issue by dongwook-chan** [23-OSSCA-python-mysql-replication/python-mysql-replication#46]
[`pymysqlreplication.tests.test_data_type.test_partition_id`](https://github.com/julien-duponchelle/python-mysql-replication/blob/45f823fa0ea6cd19de84b39aa78f5f181fafe18b/pymysqlreplication/tests/test_data_type.py#L694-L708) 테스트가 의도대로 작동하기 위해서는 MySQL 8.0.16 버전 이상의 컨테이너가 필요합니다.

해당 테스트에 대한 상세한 내용은 [PR](https://github.com/julien-duponchelle/python-mysql-replication/pull/355)을 참고해주세요

**Comment by heehehe** [comment]
저희가 진행하고 있는 mysql 8.0 기반 테스트 추가 (https://www.notion.so/open-up/mysql-8-0-5074d17acb734d538301441078af43f2?pvs=4) 와 같은 작업인거 같아서 조 label 할당해 뒀습니다 :)
