### ISSUE TITLE
오타 수정 - XAPrepareEvent

### ISSUE THREAD

**Issue by heehehe** [23-OSSCA-python-mysql-replication/python-mysql-replication#7]
contans → contains
https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/blob/92d3e6651657d7d2f2d941cd33e45fbd1437cab9/pymysqlreplication/event.py#L134-L141

**Comment by dongwook-chan** [comment]
https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/pull/8 참고하셔서 `fix-pos-individual` 브랜치로 커밋 올려주세요!

**Comment by heehehe** [comment]
https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/pull/8/commits/e5289420d488bee4b2aa85eaa34bb9ed2449ca25 로 올려뒀습니다 :)
