### ISSUE TITLE
테스트 코드 리팩터링

### ISSUE THREAD

**Issue by dongwook-chan** [23-OSSCA-python-mysql-replication/python-mysql-replication#84]
기존과 다른 Master의 벤더, 버전, 시스템 변수 환경에서 테스트하기 위해서는 많은 코드 수정이 필요합니다.
리팩터링을 통해 최소한의 코드 수정으로 새로운 테스트 환경을 구축할 수 있도록 개선이 필요합니다.

**Comment by heehehe** [comment]
https://github.com/julien-duponchelle/python-mysql-replication/pull/502 반영 완료
